In [6]:
import pandas as pd
import numpy as np
df = pd.read_csv("Stock Market Tracking.csv")
df.head()

,Stock,Market cap (in Rs Cr.),Current price,PE Ratio,52 Week High,% Below 52 week high,52 Week Low,% Above 52 Week low,Yesterday Closing Price,% Change,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,TCS,1234544.52,3374.2,30.43,4045.5,16.59%,2926,15.32%,3334.6,1.19%,...,NaN,NaN,NaN,#REF!,NaN,NaN,NaN,NaN,NaN,NaN
1,HUL,616301.33,2620.6,63.81,2741.6,4.41%,1901.55,37.81%,2590.05,1.18%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Airtel,441027.40,764.6,65.86,860.55,11.15%,628.75,21.61%,756.9,1.02%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bajaj Finance,361172.64,5977,36.52,8045,25.71%,5220,14.50%,5898.4,1.33%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Asian Paints,278960.10,2912,76.19,3582.9,18.73%,2560,13.75%,2915.95,-0.14%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
column_names = df.columns
print(column_names)

Index(['Stock', 'Market cap (in Rs Cr.)', 'Current price', 'PE Ratio',
       '52 Week High', '% Below 52 week high', '52 Week Low',
       '% Above 52 Week low', 'Yesterday Closing Price', '% Change',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24'],
      dtype='object')

In [8]:
df = df.drop(columns=['Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16','Unnamed: 17',
                      'Unnamed: 18','Unnamed: 19','Unnamed: 20','Unnamed: 21','Unnamed: 22','Unnamed: 23', 'Unnamed: 24'])
column_names = df.columns
print(column_names)

Index(['Stock', 'Market cap (in Rs Cr.)', 'Current price', 'PE Ratio',
       '52 Week High', '% Below 52 week high', '52 Week Low',
       '% Above 52 Week low', 'Yesterday Closing Price', '% Change'],
      dtype='object')

In [9]:
df.head()

,Stock,Market cap (in Rs Cr.),Current price,PE Ratio,52 Week High,% Below 52 week high,52 Week Low,% Above 52 Week low,Yesterday Closing Price,% Change
0,TCS,1234544.52,3374.2,30.43,4045.5,16.59%,2926,15.32%,3334.6,1.19%
1,HUL,616301.33,2620.6,63.81,2741.6,4.41%,1901.55,37.81%,2590.05,1.18%
2,Airtel,441027.40,764.6,65.86,860.55,11.15%,628.75,21.61%,756.9,1.02%
3,Bajaj Finance,361172.64,5977,36.52,8045,25.71%,5220,14.50%,5898.4,1.33%
4,Asian Paints,278960.10,2912,76.19,3582.9,18.73%,2560,13.75%,2915.95,-0.14%

###  Task 1 : First Create a New Sub Sheet & Fetch all the Data from the Sheet called "Data Set" where Data from the PE Ratio is not Blank & PE Ratio < 100 using Query Function  and sort the data by Descending of Market Cap Amount.

In [10]:
#=QUERY('Data Set'!A:K, "SELECT * WHERE D IS NOT NULL AND D < 100 ORDER BY B DESC", 1)


# Convert 'PE Ratio' column to numeric
df['PE Ratio'] = pd.to_numeric(df['PE Ratio'], errors='coerce')
# Filter the DataFrame to select rows where PE Ratio is not blank and less than 100
filtered_df = df[df['PE Ratio'].notnull() & (df['PE Ratio'] < 100)]
sorted_df = filtered_df.sort_values(by='Market cap (in Rs Cr.)', ascending=False)
sorted_df.to_excel('task1.xlsx', index=False)
sorted_df.sample(10)

,Stock,Market cap (in Rs Cr.),Current price,PE Ratio,52 Week High,% Below 52 week high,52 Week Low,% Above 52 Week low,Yesterday Closing Price,% Change
63,Indraprastha Gas,29162.03,416.85,17.03,466.65,10.67%,322.1,29.42%,418.6,-0.42%
204,Kotak Bank,354002.54,1780.5,25.87,1997.55,10.87%,1631,9.17%,1779.5,0.06%
213,Crisil,22166.90,3020,38.36,3863.55,21.83%,2540,18.90%,3044.5,-0.80%
2,Airtel,441027.40,764.6,65.86,860.55,11.15%,628.75,21.61%,756.9,1.02%
24,SBI Cards,74336.76,786.05,35.28,1028.65,23.58%,655.7,19.88%,780.25,0.74%
121,Sonata Software,8104.16,582,19.25,694.5,16.20%,457.58,27.19%,574.4,1.32%
31,Berger Paint,54643.26,564,57.95,793.05,28.88%,543.6,3.75%,561.95,0.36%
138,Heidelberg Cement,4230.87,186.9,23.18,242,22.77%,164,13.96%,186.85,0.03%
167,Bank of Baroda,95565.88,184.9,9.72,197.2,6.24%,89.9,105.67%,181.8,1.71%
57,MRF,38048.54,89700,66.97,95954.35,6.52%,62944.5,42.51%,89498.35,0.23%

In [11]:
sorted_df.isnull().sum()

Stock                      0
Market cap (in Rs Cr.)     0
Current price              0
PE Ratio                   0
52 Week High               0
% Below 52 week high       0
52 Week Low                0
% Above 52 Week low        0
Yesterday Closing Price    0
% Change                   0
dtype: int64

In [12]:
sorted_df.shape

(190, 10)

### Task 2 :  Now Create 2 Columns of Industry & NSE/BSE Code & Fetch Data from the Second Sheet with Vlookup, Make sure the Vlookup Formula is used with "ARRAYFORMULA" meaning formula will be written only once but will be applicable throughout the column, Also make sure the Formula of Vlookup will be applied only until when data is there in the column, handle this with IF CONDITIONS in that same formula.

In [13]:
# =IF(A1="", "", ARRAYFORMULA(VLOOKUP(A2:A, 'Company Info'!A:B, 2, FALSE)))

industry_df = pd.read_csv("NSEBSE Code.csv", skiprows=1)
industry_df.columns = industry_df.iloc[0]
industry_df = industry_df.drop(0)
industry_df = industry_df.reset_index(drop=True)
# Perform a vlook operation or merge operation with the first DataFrame
merged_df1 = pd.merge(sorted_df, industry_df, on='Stock', how='left')
# Fill missing values in the 'Industry' and 'NSE/BSE Code' columns with empty strings
merged_df1['Industry'] = merged_df1['Industry'].fillna('')
merged_df1['NSE/BSE Code'] = merged_df1['NSE/BSE Code'].fillna('')
# Save the merged DataFrame to a new CSV file
merged_df1.to_excel('task2.xlsx', index=False)
merged_df1.head()

,Stock,Market cap (in Rs Cr.),Current price,PE Ratio,52 Week High,% Below 52 week high,52 Week Low,% Above 52 Week low,Yesterday Closing Price,% Change,Industry,NSE/BSE Code
0,Tanla Platform,9951.42,731.9,19.49,2094.4,65.05%,584.8,25.15%,724.3,1.05%,Technology,BOM:532790
1,Amara Raja Batter,9847.33,576.5,17.05,668.15,13.72%,438.05,31.61%,590.95,-2.45%,Automobile Ancilliary,AMARAJABAT
2,Tech Mahindra,97631.02,1002.8,16.80,1751,42.73%,943.7,6.26%,1001.55,0.12%,IT,TECHM
3,Dabur,96383.94,544,55.79,610.75,10.93%,482.25,12.80%,544.95,-0.17%,FMCG,DABUR
4,Cyient,9606.15,876,19.98,1051.85,16.72%,720,21.67%,883.3,-0.83%,IT-Software,CYIENT

In [14]:
merged_df1.shape

(190, 12)

### Task 3 : Now Create 2 More Columns at the End with the Heading "Bear Mode 1" & "Bear Mode 2" Bear Mode 1 Condition : Use IF Condition to print "Yes" if % Change from 52 Week High > 30 else "No" Bear Mode Condition 2 : Use IF Condition to print "Yes" if % Change from 52 Week Low < 30 else "No"

In [15]:
# Convert 'Current price' and '52 Week Low' columns to numeric
merged_df1[['Current price', '52 Week High', '52 Week Low']] = merged_df1[['Current price', '52 Week High','52 Week Low']].apply(pd.to_numeric, errors='coerce')
merged_df1['% Change from 52 Week High'] = ((merged_df1['Current price'] - merged_df1['52 Week High']) / merged_df1['52 Week High']) * 100
merged_df1['% Change from 52 Week Low'] = ((merged_df1['Current price'] - merged_df1['52 Week Low']) / merged_df1['52 Week Low']) * 100
merged_df1.sample(10)

,Stock,Market cap (in Rs Cr.),Current price,PE Ratio,52 Week High,% Below 52 week high,52 Week Low,% Above 52 Week low,Yesterday Closing Price,% Change,Industry,NSE/BSE Code,% Change from 52 Week High,% Change from 52 Week Low
28,craftsman automation,7324.34,3465.10,35.75,3709.95,6.60%,1845.00,87.81%,3461.8,0.10%,automobile,BOM:543276,-6.599819,87.810298
126,Paras Defense,2250.91,577.80,67.14,811.35,28.79%,524.30,10.20%,583.75,-1.02%,Defence,BOM:543367,-28.785358,10.204082
40,Amber Enterprise,6297.53,1870.00,49.07,4023.65,53.52%,1844.15,1.40%,1876,-0.32%,Manufacturing,BOM:540902,-53.524785,1.401730
188,Bajaj Auto,101964.86,3602.45,17.79,4131.75,12.81%,3125.00,15.28%,3570.3,0.90%,Automobile,BAJAJ-AUTO,-12.810552,15.278400
71,Balkrishna Industries,43195.87,2229.00,30.72,2537.45,12.16%,1690.55,31.85%,2214.25,0.67%,Tyre,BALKRISIND,-12.155905,31.850581
9,Dr Reddy,880.69,4323.50,23.13,4759.60,9.16%,3654.00,18.32%,4310.6,0.30%,Pharma,DRREDDY,-9.162535,18.322386
67,Lux Industries,4564.43,1524.70,17.12,3925.00,61.15%,1515.10,0.63%,1526.65,-0.13%,Textile,BOM:539542,-61.154140,0.633622
45,MapmyIndia,5752.71,1071.50,65.24,1918.35,44.14%,1023.20,4.72%,1069.9,0.15%,Technology,BOM:543425,-44.144708,4.720485
62,HDFC,478914.70,2619.25,19.81,2933.80,10.72%,2026.00,29.28%,2612.8,0.25%,Financial Servcies,HDFC,-10.721590,29.281836
164,Indiamart Intermesh,13709.81,4477.00,56.62,6898.75,35.10%,3676.00,21.79%,4446.55,0.68%,Technology,INDIAMART,-35.104186,21.789989

In [16]:
# Bear Mode 1
merged_df1['Bear Mode 1'] = merged_df1['% Change from 52 Week High'].apply(lambda x: 'Yes' if x > 30 else 'No')
# Bear Mode 2
merged_df1['Bear Mode 2'] = merged_df1['% Change from 52 Week Low'].apply(lambda x: 'Yes' if x < 30 else 'No')
# Display the DataFrame to verify the changes
merged_df1.head(5)

,Stock,Market cap (in Rs Cr.),Current price,PE Ratio,52 Week High,% Below 52 week high,52 Week Low,% Above 52 Week low,Yesterday Closing Price,% Change,Industry,NSE/BSE Code,% Change from 52 Week High,% Change from 52 Week Low,Bear Mode 1,Bear Mode 2
0,Tanla Platform,9951.42,731.9,19.49,2094.40,65.05%,584.80,25.15%,724.3,1.05%,Technology,BOM:532790,-65.054431,25.153899,No,Yes
1,Amara Raja Batter,9847.33,576.5,17.05,668.15,13.72%,438.05,31.61%,590.95,-2.45%,Automobile Ancilliary,AMARAJABAT,-13.716980,31.605981,No,No
2,Tech Mahindra,97631.02,1002.8,16.80,1751.00,42.73%,943.70,6.26%,1001.55,0.12%,IT,TECHM,-42.729869,6.262583,No,Yes
3,Dabur,96383.94,544.0,55.79,610.75,10.93%,482.25,12.80%,544.95,-0.17%,FMCG,DABUR,-10.929185,12.804562,No,Yes
4,Cyient,9606.15,876.0,19.98,1051.85,16.72%,720.00,21.67%,883.3,-0.83%,IT-Software,CYIENT,-16.718163,21.666667,No,Yes

In [17]:
# Create Stock Status column
merged_df1['Stock Status'] = ''
# Apply conditions
merged_df1.loc[(df['PE Ratio'] < 65) & (merged_df1['Bear Mode 1'] == 'No') & (merged_df1['Bear Mode 2'] == 'No'), 'Stock Status'] = 'Good Stock'
# Display the DataFrame to verify the changes
merged_df1.head(5)

,Stock,Market cap (in Rs Cr.),Current price,PE Ratio,52 Week High,% Below 52 week high,52 Week Low,% Above 52 Week low,Yesterday Closing Price,% Change,Industry,NSE/BSE Code,% Change from 52 Week High,% Change from 52 Week Low,Bear Mode 1,Bear Mode 2,Stock Status
0,Tanla Platform,9951.42,731.9,19.49,2094.40,65.05%,584.80,25.15%,724.3,1.05%,Technology,BOM:532790,-65.054431,25.153899,No,Yes,
1,Amara Raja Batter,9847.33,576.5,17.05,668.15,13.72%,438.05,31.61%,590.95,-2.45%,Automobile Ancilliary,AMARAJABAT,-13.716980,31.605981,No,No,Good Stock
2,Tech Mahindra,97631.02,1002.8,16.80,1751.00,42.73%,943.70,6.26%,1001.55,0.12%,IT,TECHM,-42.729869,6.262583,No,Yes,
3,Dabur,96383.94,544.0,55.79,610.75,10.93%,482.25,12.80%,544.95,-0.17%,FMCG,DABUR,-10.929185,12.804562,No,Yes,
4,Cyient,9606.15,876.0,19.98,1051.85,16.72%,720.00,21.67%,883.3,-0.83%,IT-Software,CYIENT,-16.718163,21.666667,No,Yes,

In [18]:
merged_df1.sample(10)

,Stock,Market cap (in Rs Cr.),Current price,PE Ratio,52 Week High,% Below 52 week high,52 Week Low,% Above 52 Week low,Yesterday Closing Price,% Change,Industry,NSE/BSE Code,% Change from 52 Week High,% Change from 52 Week Low,Bear Mode 1,Bear Mode 2,Stock Status
89,Honeywell Auto,35109.69,39710.00,91.84,46397.70,14.41%,30185.35,31.55%,39677.1,0.08%,Automobile Ancilliary,HONAUT,-14.413861,31.553883,No,No,Good Stock
159,Nippon AMC,15766.34,252.60,23.69,375.20,32.68%,241.05,4.79%,251.9,0.28%,AMC,BOM:540767,-32.675906,4.791537,No,Yes,
173,Happiest Mind,12642.15,885.05,59.08,1359.85,34.92%,785.55,12.67%,884.65,0.05%,IT,BOM:543227,-34.915616,12.666285,No,Yes,
29,Metropolis Healthcare,7063.23,1380.05,45.85,3142.00,56.08%,1267.05,8.92%,1382.35,-0.17%,Healthcare,METROPOLIS,-56.077339,8.918354,No,Yes,
24,SBI Cards,74336.76,786.05,35.28,1028.65,23.58%,655.70,19.88%,780.25,0.74%,Financial Servcies,SBICARD,-23.584310,19.879518,No,Yes,
152,Goldiam International,1794.80,165.55,17.83,209.41,20.94%,116.75,41.80%,165.4,0.09%,Retail,BOM:526729,-20.944559,41.798715,No,No,
37,Praj Industries,6488.72,353.00,35.19,461.50,23.51%,289.05,22.12%,355.1,-0.59%,Manufacturing,BOM:522205,-23.510293,22.124200,No,Yes,
186,Mannapuran Finance,10287.93,121.55,8.70,173.75,30.04%,81.50,49.14%,120.15,1.17%,NBFC,MANAPPURAM,-30.043165,49.141104,No,No,Good Stock
138,Ultratech Cement,208975.80,7244.95,31.35,7946.00,8.82%,5157.05,40.49%,7153.35,1.28%,Cement,ULTRACEMCO,-8.822678,40.486325,No,No,Good Stock
165,Affle India,13659.00,1024.00,55.83,1511.00,32.23%,871.55,17.49%,1035.55,-1.12%,Technology,AFFLE,-32.230311,17.491825,No,Yes,

In [19]:
merged_df1.to_excel('task3.xlsx', index=False)

In [20]:
good_stocks = merged_df1[merged_df1['Stock Status'] == 'Good Stock']['Stock'].tolist()
print(good_stocks)

['Amara Raja Batter', 'Godrej Consumer', 'Astrazeneca', 'Eicher Motor', 'Poly Medicure Ltd', 'Granules India', 'ICICI Bank', 'Cera Sanitaryware', 'Data Pattern', 'Yesbank', 'Gujarat Ambuja Export', 'MTAR', 'PI industries', 'TVS', 'Abbott India', 'Balkrishna Industries', 'Polycab', 'Honeywell Auto', 'Somany home innovation ltd', 'Astec Lifesciences', 'Mold tech', 'APL Apollo', 'Supreme Industries', 'Gujarat Florochemical', 'Federal Bank', 'Axis Bank', 'Sun pharma', 'Sumitomo Chemicals', 'J K Cement', 'LIC Housing Finance', 'Titan', 'Ultratech Cement', 'KPIT', 'Fine Organics', 'Tata Steel', 'SBI life Insurance', 'KEI Industries', 'Finolex Industries', 'Ambuja Cement', 'Mannapuran Finance', 'UTI AMC']

In [21]:
good_stocks_df = merged_df1[merged_df1['Stock Status'] == 'Good Stock'][['Stock', 'Stock Status']]
print(good_stocks_df)

                          Stock Stock Status
1             Amara Raja Batter   Good Stock
6               Godrej Consumer   Good Stock
8                   Astrazeneca   Good Stock
11                 Eicher Motor   Good Stock
13            Poly Medicure Ltd   Good Stock
19               Granules India   Good Stock
23                   ICICI Bank   Good Stock
33            Cera Sanitaryware   Good Stock
39                 Data Pattern   Good Stock
44                      Yesbank   Good Stock
48        Gujarat Ambuja Export   Good Stock
55                         MTAR   Good Stock
58                PI industries   Good Stock
64                          TVS   Good Stock
65                 Abbott India   Good Stock
71        Balkrishna Industries   Good Stock
78                      Polycab   Good Stock
89               Honeywell Auto   Good Stock
91   Somany home innovation ltd   Good Stock
92           Astec Lifesciences   Good Stock
93                    Mold tech   Good Stock
96                   APL Apollo   Good Stock
97           Supreme Industries   Good Stock
101       Gujarat Florochemical   Good Stock
105                Federal Bank   Good Stock
107                   Axis Bank   Good Stock
120                  Sun pharma   Good Stock
121          Sumitomo Chemicals   Good Stock
127                  J K Cement   Good Stock
130         LIC Housing Finance   Good Stock
134                       Titan   Good Stock
138            Ultratech Cement   Good Stock
149                        KPIT   Good Stock
154               Fine Organics   Good Stock
162                  Tata Steel   Good Stock
167          SBI life Insurance   Good Stock
169              KEI Industries   Good Stock
182          Finolex Industries   Good Stock
185               Ambuja Cement   Good Stock
186          Mannapuran Finance   Good Stock
187                     UTI AMC   Good Stock

In [22]:
good_stocks_df.head(5)

                Stock Stock Status
1   Amara Raja Batter   Good Stock
6     Godrej Consumer   Good Stock
8         Astrazeneca   Good Stock
11       Eicher Motor   Good Stock
13  Poly Medicure Ltd   Good Stock

In [23]:
good_stocks_df.shape

(41, 2)

In [24]:
good_stocks_df.to_excel('task3.1.xlsx', index=False)

### Task 4 : Now create a new sheet & fetch all Data where Stock Status = 'Good Stock' which will be your Final Organized Data Source so Create Proper Formatting to this Sheet like the Data Source Sheet & also add Appropriate Conditional Formatting Colour Scales.

In [26]:
select_df = pd.read_excel('task2.xlsx')
selected_data = select_df[select_df['Stock'].isin(good_stocks)]
print(selected_data)

                          Stock  Market cap (in Rs Cr.)  Current price  \
1             Amara Raja Batter                 9847.33         576.50
6               Godrej Consumer                93678.86         916.75
8                   Astrazeneca                 8815.82        3515.05
11                 Eicher Motor                86543.23        3164.90
13            Poly Medicure Ltd                 8584.67         891.50
19               Granules India                 7705.43         318.60
23                   ICICI Bank                 7451.47         873.25
33            Cera Sanitaryware                 6919.97        5294.00
39                 Data Pattern                 6367.83        1227.10
44                      Yesbank                57937.94          20.15
48        Gujarat Ambuja Export                 5515.52         241.50
55                         MTAR                 5182.99        1688.15
58                PI industries                49475.63        3262.00
64                          TVS                47610.86         999.50
65                 Abbott India                47348.12       22241.00
71        Balkrishna Industries                43195.87        2229.00
78                      Polycab                39945.40        2662.00
89               Honeywell Auto                35109.69       39710.00
91   Somany home innovation ltd                 3335.19         462.25
92           Astec Lifesciences                 3279.73        1669.30
93                    Mold tech                 3279.61         988.10
96                   APL Apollo                31477.05        1136.00
97           Supreme Industries                31369.92        2461.00
101       Gujarat Florochemical                30664.63        2793.50
105                Federal Bank                29278.49         138.45
107                   Axis Bank               287213.29         933.90
120                  Sun pharma               247191.65        1031.05
121          Sumitomo Chemicals                24637.83         493.20
127                  J K Cement                22430.59        2900.45
130         LIC Housing Finance                22159.27         402.90
134                       Titan               214719.01        2417.65
138            Ultratech Cement               208975.80        7244.95
149                        KPIT                18827.95         696.30
154               Fine Organics                17277.20        5630.00
162                  Tata Steel               147293.60         120.45
167          SBI life Insurance               130568.99        1307.00
169              KEI Industries                12966.07        1436.05
182          Finolex Industries                10644.74         173.00
185               Ambuja Cement               102995.36         518.70
186          Mannapuran Finance                10287.93         121.55
187                     UTI AMC                10284.29         807.20

     PE Ratio  52 Week High % Below 52 week high  52 Week Low  \
1       17.05        668.15               13.72%       438.05
6       58.81        955.65                4.07%       660.20
8       95.35       3619.70                2.89%      2437.75
11      37.12       3889.65               18.63%      2159.55
13      61.12       1044.40               14.64%       652.30
19      16.36        381.25               16.43%       227.00
23      20.88        958.00                8.85%       642.00
33      37.00       6067.95               12.75%      3518.60
39      59.65       1480.00               17.09%       575.00
44      45.52         24.75               18.59%        12.11
48      12.67        393.85               38.68%       169.25
55      70.16       2409.15               29.93%      1211.85
58      48.33       3698.45               11.80%      2333.55
64      39.03       1177.00               15.08%       513.00
65      53.60      22499.00                1.15%     15514.00
71      30.72       2537.45               12.16%      1690.55
78      35.50       3025.00               12.00%      2043.85
89      91.84      46397.70               14.41%     30185.35
91      33.36        480.40                3.78%       258.95
92      33.56       2285.65               26.97%      1276.15
93      41.73       1057.85                6.59%       648.05
96      54.90       1193.85                4.85%       771.00
97      36.12       2607.65                5.62%      1666.25
101     28.23       4172.95               33.06%      2105.15
105     11.78        142.25                2.67%        82.50
107     15.67        970.00                3.72%       618.25
120     60.40       1070.95                3.73%       784.80
121     48.90        540.80                8.80%       351.50
127     36.07       3646.25               20.45%      2005.00
130      6.85        443.50                9.15%       291.75
134     68.59       2790.00               13.35%      1827.15
138     31.35       7946.00                8.82%      5157.05
149     59.82        764.25                8.89%       440.00
154     32.19       7328.75               23.18%      3457.10
162      5.13        138.63               13.11%        82.71
167     78.07       1340.35                2.49%      1003.50
169     30.59       1662.45               13.62%       905.20
182     15.85        204.50               15.40%       128.00
185     57.36        598.15               13.28%       274.00
186      8.70        173.75               30.04%        81.50
187     21.59       1096.05               26.35%       595.00

    % Above 52 Week low  Yesterday Closing Price % Change  \
1                31.61%                   590.95   -2.45%
6                38.86%                   914.90    0.20%
8                44.19%                  3443.40    2.08%
11               46.55%                  3103.25    1.99%
13               36.67%                   897.90   -0.71%
19               40.35%                   318.15    0.14%
23               36.02%                   861.20    1.40%
33               50.46%                  5320.00   -0.49%
39              113.41%                  1161.25    5.67%
44               66.39%                    19.90    1.26%
48               42.69%                   236.70    2.03%
55               39.30%                  1670.50    1.06%
58               39.79%                  3292.65   -0.93%
64               94.83%                  1005.20   -0.57%
65               43.36%                 22162.55    0.35%
71               31.85%                  2214.25    0.67%
78               30.24%                  2677.05   -0.56%
89               31.55%                 39677.10    0.08%
91               78.51%                   473.20   -2.31%
92               30.81%                  1635.25    2.08%
93               52.47%                   991.35   -0.33%
96               47.34%                  1127.95    0.71%
97               47.70%                  2452.70    0.34%
101              32.70%                  2841.60   -1.69%
105              67.82%                   135.05    2.52%
107              51.06%                   935.55   -0.18%
120              31.38%                  1032.85   -0.17%
121              40.31%                   487.95    1.08%
127              44.66%                  2905.90   -0.19%
130              38.10%                   400.20    0.67%
134              32.32%                  2445.65   -1.14%
138              40.49%                  7153.35    1.28%
149              58.25%                   692.45    0.56%
154              62.85%                  5672.25   -0.74%
162              45.63%                   118.05    2.03%
167              30.24%                  1315.70   -0.66%
169              58.64%                  1435.20    0.06%
182              35.16%                   170.90    1.23%
185              89.31%                   510.40    1.63%
186              49.14%                   120.15    1.17%
187              35.66%                   812.90   -0.70%

                  Industry NSE/BSE Code
1    Automobile Ancilliary   AMARAJABAT
6                     FMCG   BOM:532424
8                   Pharma   BOM:506820
11              Automobile    EICHERMOT
13              Healthcare   BOM:531768
19                  Pharma   BOM:532482
23                    Bank   BOM:532174
33                Ceramics   BOM:532443
39              Technology   BOM:543428
44                    Bank   BOM:532648
48                     NaN   BOM:524226
55                 Defence   BOM:543270
58            Agrochemical        PIIND
64              Automobile   BOM:532343
65                  Pharma   ABBOTINDIA
71                    Tyre   BALKRISIND
78     Consumer Electrical      POLYCAB
89   Automobile Ancilliary       HONAUT
91      Kitchen Appliances   BOM:542905
92                  Pharma   BOM:533138
93                     NaN   BOM:533080
96                   Steel   BOM:533758
97                 Plastic   SUPREMEIND
101               chemical   BOM:542812
105                   Bank   BOM:500469
107                   Bank     AXISBANK
120                 Pharma    SUNPHARMA
121           Agrochemical     SUMICHEM
127                 Cement   BOM:532644
130                   NBFC   BOM:500253
134                 Retail   BOM:500114
138                 Cement   ULTRACEMCO
149                     IT   BOM:542651
154               Chemical      FINEORG
162         Infrastructure   BOM:500470
167              Insurance      SBILIFE
169    Consumer Electrical   BOM:517569
182                 Piping   BOM:500940
185                 Cement   BOM:500425
186                   NBFC   MANAPPURAM
187                    AMC   BOM:543238

In [27]:
selected_data.head(5)

,Stock,Market cap (in Rs Cr.),Current price,PE Ratio,52 Week High,% Below 52 week high,52 Week Low,% Above 52 Week low,Yesterday Closing Price,% Change,Industry,NSE/BSE Code
1,Amara Raja Batter,9847.33,576.50,17.05,668.15,13.72%,438.05,31.61%,590.95,-2.45%,Automobile Ancilliary,AMARAJABAT
6,Godrej Consumer,93678.86,916.75,58.81,955.65,4.07%,660.20,38.86%,914.90,0.20%,FMCG,BOM:532424
8,Astrazeneca,8815.82,3515.05,95.35,3619.70,2.89%,2437.75,44.19%,3443.40,2.08%,Pharma,BOM:506820
11,Eicher Motor,86543.23,3164.90,37.12,3889.65,18.63%,2159.55,46.55%,3103.25,1.99%,Automobile,EICHERMOT
13,Poly Medicure Ltd,8584.67,891.50,61.12,1044.40,14.64%,652.30,36.67%,897.90,-0.71%,Healthcare,BOM:531768

In [28]:
selected_data.to_excel('task4.xlsx', index=False)

### Task 5 : Create a Pivot Table Report as Follows :

- Industry wise Total Count of Companies
- Industry wise Average Market Cap
- Industry wise sum of Market Cap

In [35]:
pivot_table_count = pd.pivot_table(selected_data, 
                                    index='Industry',
                                    values='Stock',
                                    aggfunc='count',
                                    fill_value=0)

# Rename the column for better readability
pivot_table_count.columns = ['Total Count of Companies according to Industry']
# print(pivot_table_count)
pivot_table_count.head(100)

                       Total Count of Companies according to Industry
Industry
AMC                                                                 1
Agrochemical                                                        2
Automobile                                                          2
Automobile Ancilliary                                               2
Bank                                                                4
Cement                                                              3
Ceramics                                                            1
Chemical                                                            1
Consumer Electrical                                                 2
Defence                                                             1
FMCG                                                                1
Healthcare                                                          1
IT                                                                  1
Infrastructure                                                      1
Insurance                                                           1
Kitchen Appliances                                                  1
NBFC                                                                2
Pharma                                                              5
Piping                                                              1
Plastic                                                             1
Retail                                                              1
Steel                                                               1
Technology                                                          1
Tyre                                                                1
chemical                                                            1

In [36]:
pivot_table_count.to_excel('task5.1.xlsx')

In [37]:
pivot_table_count2 = pd.pivot_table(selected_data, 
                                    index='Industry',
                                    values='Market cap (in Rs Cr.)',
                                    aggfunc='mean',
                                    fill_value=0)

# Rename the column for better readability
pivot_table_count2.columns = ['Average Market Cap based on Industry']
print(pivot_table_count2)
pivot_table_count2.head()

                       Average Market Cap based on Industry
Industry
AMC                                              10284.2900
Agrochemical                                     37056.7300
Automobile                                       67077.0450
Automobile Ancilliary                            22478.5100
Bank                                             95470.2975
Cement                                          111467.2500
Ceramics                                          6919.9700
Chemical                                         17277.2000
Consumer Electrical                              26455.7350
Defence                                           5182.9900
FMCG                                             93678.8600
Healthcare                                        8584.6700
IT                                               18827.9500
Infrastructure                                  147293.6000
Insurance                                       130568.9900
Kitchen Appliances                                3335.1900
NBFC                                             16223.6000
Pharma                                           62868.1500
Piping                                           10644.7400
Plastic                                          31369.9200
Retail                                          214719.0100
Steel                                            31477.0500
Technology                                        6367.8300
Tyre                                             43195.8700
chemical                                         30664.6300

                       Average Market Cap based on Industry
Industry
AMC                                              10284.2900
Agrochemical                                     37056.7300
Automobile                                       67077.0450
Automobile Ancilliary                            22478.5100
Bank                                             95470.2975

In [39]:
pivot_table_count2.to_excel('task5.2.xlsx')

In [33]:
pivot_table_count3 = pd.pivot_table(selected_data, 
                                    index='Industry',
                                    values='Market cap (in Rs Cr.)',
                                    aggfunc='sum',
                                    fill_value=0)

# Rename the column for better readability
pivot_table_count3.columns = ['SUM of Market Cap based on Industry']
print(pivot_table_count3)
pivot_table_count3.head()

                       SUM of Market Cap based on Industry
Industry
AMC                                               10284.29
Agrochemical                                      74113.46
Automobile                                       134154.09
Automobile Ancilliary                             44957.02
Bank                                             381881.19
Cement                                           334401.75
Ceramics                                           6919.97
Chemical                                          17277.20
Consumer Electrical                               52911.47
Defence                                            5182.99
FMCG                                              93678.86
Healthcare                                         8584.67
IT                                                18827.95
Infrastructure                                   147293.60
Insurance                                        130568.99
Kitchen Appliances                                 3335.19
NBFC                                              32447.20
Pharma                                           314340.75
Piping                                            10644.74
Plastic                                           31369.92
Retail                                           214719.01
Steel                                             31477.05
Technology                                         6367.83
Tyre                                              43195.87
chemical                                          30664.63

                       SUM of Market Cap based on Industry
Industry
AMC                                               10284.29
Agrochemical                                      74113.46
Automobile                                       134154.09
Automobile Ancilliary                             44957.02
Bank                                             381881.19

In [40]:
pivot_table_count3.to_excel('task5.3.xlsx')